default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: Calendar_late

test:
  <<: *default
  database: Calendar_late

production:
  <<: *default
  database: MicroPost_production
  username: MicroPost
  password: <%= ENV['MICROPOST_DATABASE_PASSWORD'] %>



