default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: TestUser
  password: test
  pool: 5

development:
  <<: *default
  database: Calendar

test:
  <<: *default
  database: Calendar

production:
  <<: *default
  database: MicroPost_production
  username: MicroPost
  password: <%= ENV['MICROPOST_DATABASE_PASSWORD'] %>



